In [1]:
import torch

In [2]:
torch.manual_seed(7)

In [8]:
features = torch.randn((1,5))

In [9]:
weights = torch.randn_like(features)

In [10]:
bias = torch.randn((1,1))

In [11]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [14]:
# One perceptron
y = activation(torch.sum(weights * features) + bias)
y

tensor([[0.4722]])

In [15]:
y = activation(torch.mm(weights, features) + bias)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:2070

In [16]:
weights.shape

torch.Size([1, 5])

In [17]:
weights.view(5,1)

tensor([[ 1.7792],
        [-0.9179],
        [-0.4578],
        [-0.7245],
        [ 1.2799]])

In [20]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [21]:
y

tensor([[0.4722]])